spring.application.name=FoodieDrop

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=foodiedrop

# Server Configuration
server.port=8080
